/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizationRouteImport } from './routes/visualization'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadExpenseRouteImport } from './routes/upload.expense'
import { Route as UploadAdvanceRouteImport } from './routes/upload.advance'
import { Route as ExpensesIdRouteImport } from './routes/expenses.$id'

const VisualizationRoute = VisualizationRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadExpenseRoute = UploadExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => UploadRoute,
} as any)
const UploadAdvanceRoute = UploadAdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => UploadRoute,
} as any)
const ExpensesIdRoute = ExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRouteWithChildren
  '/visualization': typeof VisualizationRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/upload/advance': typeof UploadAdvanceRoute
  '/upload/expense': typeof UploadExpenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRouteWithChildren
  '/visualization': typeof VisualizationRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/upload/advance': typeof UploadAdvanceRoute
  '/upload/expense': typeof UploadExpenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRouteWithChildren
  '/visualization': typeof VisualizationRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/upload/advance': typeof UploadAdvanceRoute
  '/upload/expense': typeof UploadExpenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/upload'
    | '/visualization'
    | '/expenses/$id'
    | '/upload/advance'
    | '/upload/expense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/upload'
    | '/visualization'
    | '/expenses/$id'
    | '/upload/advance'
    | '/upload/expense'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/upload'
    | '/visualization'
    | '/expenses/$id'
    | '/upload/advance'
    | '/upload/expense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  UploadRoute: typeof UploadRouteWithChildren
  VisualizationRoute: typeof VisualizationRoute
  ExpensesIdRoute: typeof ExpensesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualization': {
      id: '/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof VisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/expense': {
      id: '/upload/expense'
      path: '/expense'
      fullPath: '/upload/expense'
      preLoaderRoute: typeof UploadExpenseRouteImport
      parentRoute: typeof UploadRoute
    }
    '/upload/advance': {
      id: '/upload/advance'
      path: '/advance'
      fullPath: '/upload/advance'
      preLoaderRoute: typeof UploadAdvanceRouteImport
      parentRoute: typeof UploadRoute
    }
    '/expenses/$id': {
      id: '/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof ExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UploadRouteChildren {
  UploadAdvanceRoute: typeof UploadAdvanceRoute
  UploadExpenseRoute: typeof UploadExpenseRoute
}

const UploadRouteChildren: UploadRouteChildren = {
  UploadAdvanceRoute: UploadAdvanceRoute,
  UploadExpenseRoute: UploadExpenseRoute,
}

const UploadRouteWithChildren =
  UploadRoute._addFileChildren(UploadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  UploadRoute: UploadRouteWithChildren,
  VisualizationRoute: VisualizationRoute,
  ExpensesIdRoute: ExpensesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
